### ISSUE TITLE
Dataset problems

### ISSUE THREAD

**Issue by stepByStepToSky** [csjcai/SICE#1]
thanks for your kindness to make such a dataset, could you please release your rest dataset parts. thaks

**Comment by csjcai** [comment]
We had released the dataset.

**Comment by nitinkapgate** [comment]
The images in part 1 and part 2 of the dataset are the same (360 images each in both of the datasets, not 229 images in the second dataset as it should be). Please check
Google Drive: Part1: 360 Image Sequences, Part2: 229 Image Sequences
![image](https://user-images.githubusercontent.com/10544183/57350747-e6963d80-717c-11e9-8cd1-cd72b45f86bb.png)
