### ISSUE TITLE
Can you provide the WLSFilter parameters?

### ISSUE THREAD

**Issue by oneTaken** [csjcai/SICE#4]
Thanks for your fancy work.

I just want to use your paper to do enhancement for my night photos.
Because you don't provide the pretrained model, I have to try my best to reimplement your paper by my self. And I found the code in WLSFilter to split one gray image to low frequency and high frequency, how about the WLSFilter params? I try some combinations, and do not get good results.

Q1:Can you provide the **WLSFilter params** or the processed images?

~~Q2:By the way, the author WLSFilter is doing on **gray** image, how to process on the **RGB** image?~~

**Comment by csjcai** [comment]
We had uploaded the code and we use the default setting of WLSFilter.
