### ISSUE TITLE
Split under-exposed and over-exposed images?

### ISSUE THREAD

**Issue by oneTaken** [csjcai/SICE#5]
In the **Section V** and **Part B**, the last line is(corresponding to the **Table V** results):

> Note that for all the methods, we set the different model parameters for under-exposed and over-exposed images.

And I download your provided dataset, there is just a dim `.txt` file to describe the test phase.
Can you give a more clear description to split the under or over exposed images?
Or more directly just give the two name filelist in `.txt` file.

**Comment by csjcai** [comment]
We upload the training and testing code and the trained model.
You can test the image by yourself.
