### ISSUE TITLE
train data pairs

### ISSUE THREAD

**Issue by xiaonaa** [csjcai/SICE#8]
Hi, I would like to ask you what is the fully aligned low-light input image of the label when you are training. I have seen several images and found that the corresponding low-light image's Number of the label are different. Because it is difficult to align them one by one, I would like to ask you to tell me. thank you!

**Comment by csjcai** [comment]
The network is robust to the training data. We take images of -1, -2 ev as input for the low light enhancement network training. It is not necessary to 100% aligned the input and the label.

**Comment by xiaonaa** [comment]
I see. Thank you!
